- name: Ensure Python venv is installed
  apt:
    name: python3-venv
    state: present
    update_cache: yes

- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /home/pi/venv
    creates: /home/pi/venv

- name: Install Python requirements
  ansible.builtin.pip:
    requirements: /home/pi/requirements.txt
    virtualenv: /home/pi/venv
    virtualenv_python: python3

- name: Copy Python script
  ansible.builtin.copy:
    src: rpi_monitor.py
    dest: /home/pi/rpi_monitor.py
    mode: '0755'

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: /home/pi/requirements.txt

- name: Copy systemd service file
  template:
    src: rpi_monitor.service.j2
    dest: /etc/systemd/system/rpi_monitor.service
    mode: '0644'

- name: Enable and start service
  systemd:
    name: rpi_monitor.service
    enabled: true
    state: restarted
    daemon_reload: yes
